server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: lequanghuy2212
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      password: none
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
springdoc:
  api-docs:
    path: /api-docs
